version: 0.1

environment_variables:
  plaintext:
    PACKER_NO_COLOR: "1"

phases:
  install:
    commands:
      - apt-get update || echo "Failed to run apt-get update."
      - apt-get install jq -y || echo "Failed to install and/or update jq."
      - echo "Installing HashiCorp Packer from latest available version..."
      - packer_url=$(curl https://releases.hashicorp.com/index.json | jq '{packer}' | egrep "linux.*amd64" | sort --version-sort -r | head -1 | awk -F[\"] '{print $4}')
      - echo "Packer url $packer_url"
      - packer_url="https://releases.hashicorp.com/packer/1.4.3/packer_1.4.3_linux_amd64.zip"
      - echo "curl -qL -o packer.zip $packer_url && unzip -o packer.zip"
      - curl -qL -o packer.zip $packer_url && unzip -o packer.zip
      - mv ./packer /usr/bin
      - packer --version
      - rm -rf packer.zip
  pre_build:
    commands:
      - curl -qL 169.254.170.2/$AWS_CONTAINER_CREDENTIALS_RELATIVE_URI > credentials.json
      - mkdir -p ~/.aws
      - echo "[default]" > ~/.aws/credentials
      - echo "aws_access_key_id = $(cat credentials.json | jq '.AccessKeyId' | sed s'/"//g')" >> ~/.aws/credentials
      - echo "aws_secret_access_key = $(cat credentials.json | jq '.SecretAccessKey' | sed s'/"//g')" >> ~/.aws/credentials
      - echo "aws_session_token = $(cat credentials.json | jq '.Token' | sed s'/"//g')" >> ~/.aws/credentials
  build:
    commands:
      - 
      - /usr/bin/packer build -var "aws_region=ap-southeast-2" "deploy/packerwindows.json"
