---
AWSTemplateFormatVersion: '2010-09-09'
Description: AMI Builder Template
Parameters:
  RepositoryOwner:
    Description: Name for Github account.
    Type: String
    Default: davidtpwilliams
  RepositoryName:
    Description: Name for the CodeCommit repository.
    Type: String
    Default: packer-ami-pipeline
  OAuthToken:
    Description: Credentials to access repo.
    Type: String
  RepositoryDescription:
    Description: A description to set on the CodeCommit created repository.
    Type: String
    Default: AMI Builder repository stuff.
  PipelineName:
    Description: The name of your AWS CodePipeline pipeline.
    Type: String
    Default: ami-builder
  RepositoryBranch:
    Description: The name of the branch to pull source from.
    Type: String
    Default: master
  ProjectName:
    Description: A name for the project. The name must be unique across all of the
      projects in your AWS account.
    Type: String
    Default: ami-builder
  CodeBuildImage:
    Description: The Docker image identifier that the build environment uses.
    Type: String
    Default: aws/codebuild/ubuntu-base:14.04
Resources:
  PipelineBucket:
    Type: AWS::S3::Bucket
    Properties:
      VersioningConfiguration:
        Status: Enabled
  CodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name:
        Ref: ProjectName
      ServiceRole:
        Fn::ImportValue: CodeBuildRoleARN
      Environment:
        Image:
          Ref: CodeBuildImage
        ComputeType: BUILD_GENERAL1_SMALL
        Type: LINUX_CONTAINER
      Source:
        Type: CODEPIPELINE
      Artifacts:
        Type: CODEPIPELINE
  Pipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name:
        Ref: PipelineName
      RoleArn:
        Fn::ImportValue: CodePipelineRoleARN
      ArtifactStore:
        Type: S3
        Location:
          Ref: PipelineBucket
      Stages:
      - Name: Source
        Actions:
        - Name: Source
          ActionTypeId:
            Category: Source
            Owner: ThirdParty
            Version: 1
            Provider: GitHub
          Configuration:
            Owner: !Ref RepositoryOwner
            Repo: !Ref RepositoryName
            Branch: !Ref RepositoryBranch
            OAuthToken: !Ref OAuthToken
          OutputArtifacts:
          - Name: ami-builder-github
          RunOrder: 1
      - Name: Build
        Actions:
        - Name: Build
          ActionTypeId:
            Category: Build
            Owner: AWS
            Version: '1'
            Provider: CodeBuild
          Configuration:
            ProjectName:
              Ref: CodeBuildProject
          InputArtifacts:
          - Name: ami-builder-github
          OutputArtifacts:
          - Name: ami-builder-codebuild
          RunOrder: 1
