---
AWSTemplateFormatVersion: '2010-09-09'
Description: AMI Builder Role Template
Parameters:
  CodePipelineRoleName:
    Description: Name for the CodePipeline Role.
    Type: String
    Default: AWS-CodePipeline-Service
  CodeBuildRoleName:
    Description: Name for the CodePipeline Role.
    Type: String
    Default: AWS-CodeBuild-Service
Resources:
  CodePipelineRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName:
        Ref: CodePipelineRoleName
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service: codepipeline.amazonaws.com
          Action: sts:AssumeRole
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/AWSCodePipelineFullAccess
      - arn:aws:iam::aws:policy/AWSCodeCommitFullAccess
      - arn:aws:iam::aws:policy/AWSCodeBuildDeveloperAccess
      - arn:aws:iam::aws:policy/AmazonS3FullAccess
  CodeBuildRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName:
        Ref: CodeBuildRoleName
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service: codebuild.amazonaws.com
          Action: sts:AssumeRole
      ManagedPolicyArns:
      - arn:aws:iam::aws:policy/AWSCodeBuildReadOnlyAccess
      - arn:aws:iam::aws:policy/CloudWatchLogsFullAccess
      - arn:aws:iam::aws:policy/AmazonS3FullAccess
      - arn:aws:iam::aws:policy/AmazonEC2FullAccess
Outputs:
  CodePipelineRoleARN:
    Value:
      Fn::GetAtt:
      - CodePipelineRole
      - Arn
    Export:
      Name: CodePipelineRoleARN
  CodeBuildRoleARN:
    Value:
      Fn::GetAtt:
      - CodeBuildRole
      - Arn
    Export:
      Name: CodeBuildRoleARN
